### ISSUE TITLE
speller.get('encoding') occasionally returns 'none'

### ISSUE THREAD

**Issue by wingrunr21** [YorickPeterse/ffi-aspell#24]
Hi,

We are having an issue after moving to `ffi-aspell` from `raspell`. We are seeing a consistent exception regarding the Aspell encoding setting: `ArgumentError: unknown encoding name - none`. This appears to be happening as a result of the [`force_encoding`](https://github.com/YorickPeterse/ffi-aspell/blob/master/lib/ffi/aspell/speller.rb#L396) call in `handle_output`. However, the stack trace indicates the exception is being triggered in `new`. As far as I can see, `handle_output` is only called when the `suggestions` method is used. We are only using the `correct?` method.

Full `ffi-aspell` implementation:

```ruby
class Spellchecker
  # Given a block of text, return an array of misspelled words
  def self.misspellings(text)
    speller = FFI::Aspell::Speller.new('en_US')
    begin
      return text.scan(/[\w\']+/).reject do |word|
        speller.correct?(word)
      end
    ensure
      speller.close
    end
  end
end
```

Stack trace:

```
1 File "/u01/app/jsLab_server/shared/bundled_gems/ruby/2.1.0/gems/ffi-aspell-1.1.0/lib/ffi/aspell/speller.rb" line 396 in force_encoding
2 File "/u01/app/jsLab_server/shared/bundled_gems/ruby/2.1.0/gems/ffi-aspell-1.1.0/lib/ffi/aspell/speller.rb" line 396 in handle_output
3 File "/u01/app/jsLab_server/shared/bundled_gems/ruby/2.1.0/gems/ffi-aspell-1.1.0/lib/ffi/aspell/speller.rb" line 461 in available_dictionaries
4 File "/u01/app/jsLab_server/shared/bundled_gems/ruby/2.1.0/gems/ffi-aspell-1.1.0/lib/ffi/aspell/speller.rb" line 202 in dictionary_available?
5 File "/u01/app/jsLab_server/shared/bundled_gems/ruby/2.1.0/gems/ffi-aspell-1.1.0/lib/ffi/aspell/speller.rb" line 420 in check_dictionary
6 File "/u01/app/jsLab_server/shared/bundled_gems/ruby/2.1.0/gems/ffi-aspell-1.1.0/lib/ffi/aspell/speller.rb" line 443 in update_speller
7 File "/u01/app/jsLab_server/shared/bundled_gems/ruby/2.1.0/gems/ffi-aspell-1.1.0/lib/ffi/aspell/speller.rb" line 305 in set
8 File "/u01/app/jsLab_server/shared/bundled_gems/ruby/2.1.0/gems/ffi-aspell-1.1.0/lib/ffi/aspell/speller.rb" line 160 in block in initialize
9 File "/u01/app/jsLab_server/shared/bundled_gems/ruby/2.1.0/gems/ffi-aspell-1.1.0/lib/ffi/aspell/speller.rb" line 160 in each
10 File "/u01/app/jsLab_server/shared/bundled_gems/ruby/2.1.0/gems/ffi-aspell-1.1.0/lib/ffi/aspell/speller.rb" line 160 in initialize
11 File "/u01/app/jsLab_server/releases/20160114185215/lib/spelling/spellchecker.rb", line 4 in new
12 File "/u01/app/jsLab_server/releases/20160114185215/lib/spelling/spellchecker.rb", line 4 in misspellings
```

Some debug information:

```bash
> aspell --version
@(#) International Ispell Version 3.1.20 (but really Aspell 0.60.7-20110707)
> aspell config encoding 
UTF-8
```

```ruby
FFI::Aspell::Speller.new('en_US').get('encoding') => 'UTF-8'
```

Thanks!

**Comment by YorickPeterse** [comment]
Could you provide sample input that triggers the above error?

**Comment by wingrunr21** [comment]
It is only triggered when being run through a Rails controller action. Examples:

"Design has been sized up and adjusted to yield the best results."
"Design has been simplified and adjusted to yield the best results."
"We have used a dark red color that closely resembles your original upload color."
"A thin transparent outline has been added to the overlapping areas in your design."

Rails/Ruby also expect UTF-8 encoding for Strings.

**Comment by YorickPeterse** [comment]
The following all appears to work fine:

```ruby
require 'ffi/aspell'

speller = FFI::Aspell::Speller.new('en_US')

strings = [
  "Design has been sized up and adjusted to yield the best results.",
  "Design has been simplified and adjusted to yield the best results.",
  "We have used a dark red color that closely resembles your original upload color.",
  "A thin transparent outline has been added to the overlapping areas in your design."
]

strings.each do |string|
  p speller.correct?(string)
end
```

Without a script that reproduces the exact error there's sadly little I can do.

**Comment by wingrunr21** [comment]
Well that's the thing, we can't reproduce it ourselves either in Rails console or in a manual script. We've thrown a ton of text at it. The `none` setting is definitely coming from Aspell.

**Comment by YorickPeterse** [comment]
Oh I believe you've tried to reproduce it, but I can't guess what's going on myself and I don't have access to whatever input you're throwing at it. As such I can't really do anything at the moment.

**Comment by wingrunr21** [comment]
Looking over the Aspell source, it appears to have two different definitions for `get_encoding` (determined at compile time). One simply always returns 'none' and the other will return none if it determines a given codeset is ascii. I'm guessing this is an Aspell bug.

As a fix, we may try manually specify the encoding in the constructor rather than relying on Aspell to return it correctly.

**Comment by wingrunr21** [comment]
Wanted to give an update on this:

We deployed a change that specifically set the encoding in the speller constructor. This has resolved the issue. So, to be clear, it appears that even if Aspell itself has its encoding set to `UTF-8`, fetching that encoding from the config does not appear to be reliable. As Ruby has no notion of an encoding called `none`, you will end up getting an exception whenever the value of `get('encoding')` is used and a bad value is returned.

**Comment by pavelkim** [comment]
Had the same issue on a fresh linux box (lxc, centos template).
There was no LANG defined in the environment. 

Fix for me:
```
$ cat /etc/environment 
LANG="en_US.UTF-8"
LC_ALL="en_US.UTF-8"
```
